import argparse
from dataclasses import dataclass, field
from enum import Enum
import json
from pathlib import Path
import pprint
import sys

from .config import IdentifierConfig
from .asc_frame import parse_asc_frame
from .id2bus_map import Id2BusMap
from .utils import int_canid_to_hex

@dataclass
class BusResolveState:
    bus_number: str
    candidates: set[str] | None = None
    matched_ids: set[int] = field(default_factory=set)
    ignored_ids: set[int] = field(default_factory=set)
    unknown_ids: set[int] = field(default_factory=set)

    def observe(self, can_id: int, labels: set[str]) -> None:
        if self.candidates is None:
            self.candidates = set(labels)
        else:
            self.candidates &= labels

        self.matched_ids.add(can_id)

    def ignore(self, can_id: int) -> None:
        self.ignored_ids.add(can_id)
    
    def unknown(self, can_id: int) -> None:
        self.unknown_ids.add(can_id)

class ResolveResult(Enum):
    RESOLVED = "resolved"
    MULTIPLE_CANDIDATES = "multiple candidates"
    NO_CANDIDATES = "no candidates"
    NO_VALID_ID_FOUND = "no valid id found"

def format_output(states: dict[str, BusResolveState], verbosity: int) -> list[dict]:
    results: list[dict] = []
    for bus_number in sorted(states.keys(), key=lambda x: int(x)):
        state = states[bus_number]

        labels = []
        if state.candidates is None:
            result = ResolveResult.NO_VALID_ID_FOUND
        else:
            labels = sorted(state.candidates)
            label_count = len(labels)
            if label_count == 1:
                result = ResolveResult.RESOLVED
            elif label_count == 0:
                result = ResolveResult.NO_CANDIDATES
            else:
                result = ResolveResult.MULTIPLE_CANDIDATES

        result_item = {
            "bus_number": bus_number,
            "result": result.value,
            "labels": labels,
        }

        if verbosity >= 1:
            result_item["matched_ids"] = [int_canid_to_hex(id) for id in sorted(state.matched_ids)]
            result_item["ignored_ids"] = [int_canid_to_hex(id) for id in sorted(state.ignored_ids)]
            result_item["unknown_ids"] = [int_canid_to_hex(id) for id in sorted(state.unknown_ids)]

        results.append(result_item)
    
    return results

def apply_unique_label_resolution(states: dict[str, BusResolveState]) -> None:
    changed = True
    while changed:
        changed = False
        resolved_labels = {
            sorted(state.candidates)[0]
            for state in states.values()
            if state.candidates and len(state.candidates) == 1
        }

        for state in states.values():
            if state.candidates is None or len(state.candidates) <= 1:
                continue

            before = set(state.candidates)
            after = before - resolved_labels

            if before != after:
                state.candidates = after
                changed = True
    
def resolve_bus_labels(
        input_asc: str,
        id2bus_json: str,
        config_json: str | None,
        unique_label: bool,
        max_frames: int,
        verbosity: int,
        ignore_unknown_ids: bool
    ) -> list[dict]:
    id2bus = Id2BusMap.load_json(id2bus_json)
    ignore_config = IdentifierConfig.load_json(config_json)

    states: dict[str, BusResolveState] = {}

    with Path(input_asc).open("r", encoding="utf-8") as fp:
        parsed_line_cnt = 0
        for line in fp:          
            frame = parse_asc_frame(line)
            if frame is None:
                continue

            parsed_line_cnt += 1

            if parsed_line_cnt > max_frames:
                break

            if frame.bus_number not in states:
                states[frame.bus_number] = BusResolveState(
                    bus_number = frame.bus_number
                )
            state = states[frame.bus_number]

            can_id = frame.can_id
            if ignore_config.match_ignore_rules(can_id):
                state.ignore(can_id)
                continue

            mapped_labels = id2bus.get_labels(frame.can_id)
            if mapped_labels is None:
                state.unknown(can_id)
                if ignore_unknown_ids:
                    continue
                else:
                    mapped_labels = set()

            state.observe(can_id, mapped_labels)
    
    if unique_label:
        apply_unique_label_resolution(states)
    
    results: list[dict] = format_output(states, verbosity)
    return results

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input_asc", help="Input ASC file")
    parser.add_argument("id2bus_json", help="JSON file generated by generate_id2bus_map.py")
    parser.add_argument("-O", "--output", help="output file")
    parser.add_argument("-c", "--config-json", help="Configuration file for adding settings such as ignore IDs")
    parser.add_argument("-u", "--unique-label", action="store_true", help="if true, assume that the bus appears on only one interface")
    parser.add_argument("-m", "--max-frames", type=int, default=10000, help="Maximum number of ASC frames to read")
    parser.add_argument("-v", "--verbosity", action="count", default=0, help="increase output verbosity")
    parser.add_argument("--ignore-unknown-ids",action="store_true",help="Ignore CAN IDs that are not found in the id2bus map",)
    args = parser.parse_args()

    asc_busmap = resolve_bus_labels(
        args.input_asc,
        args.id2bus_json,
        args.config_json,
        args.unique_label,
        args.max_frames,
        args.verbosity,
        args.ignore_unknown_ids
    ) 

    if args.output:
        with open(args.output, "w", encoding="utf-8") as fp:
            json.dump(asc_busmap, fp, ensure_ascii=False, indent=2)
    else:
        pprint.pprint(asc_busmap)

    return 0

if __name__ == '__main__':
    sys.exit(main())