import argparse
import json
import pprint
import sys
from pathlib import Path

from .bus_resolver import resolve_bus_labels
from .id2bus_map import Id2BusMap

def write_json_or_print(data: dict | list, output: str | None) -> None:
    if output:
        with Path(output).open("w", encoding="utf-8") as fp:
            json.dump(data, fp, ensure_ascii=False, indent=2)
    else:
        pprint.pprint(data)

def run_generate_id2bus(args: argparse.Namespace) -> int:
    id2bus = Id2BusMap.from_dbc_with_label_map_json(
        args.files,
        args.label_map,
    ).to_json_dict()

    write_json_or_print(id2bus, args.output)
    return 0

def run_identify(args: argparse.Namespace) -> int:
    result = resolve_bus_labels(
        input_asc=args.input_asc,
        id2bus_json=args.id2bus_json,
        config_json=args.config_json,
        unique_label=args.unique_label,
        max_frames=args.max_frames,
        verbosity=args.verbosity,
        ignore_unknown_ids=args.ignore_unknown_ids,
    )

    write_json_or_print(result, args.output)
    return 0

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="can_bus_identifier",
        description="Identify CAN bus labels from DBC files and ASC logs.",
    )

    subparsers = parser.add_subparsers(dest="command", required=True)

    generate_parser = subparsers.add_parser("generate-id2bus", help="Generate id2bus JSON from DBC files.")
    generate_parser.add_argument("-L", "--label-map", required=True, help="JSON file containing file pattern to bus label mapping.")
    generate_parser.add_argument("-O", "--output", help="Output JSON file.")
    generate_parser.add_argument("files", nargs="+", help="DBC files or glob patterns.")
    generate_parser.set_defaults(func=run_generate_id2bus)

    identify_parser = subparsers.add_parser("identify", help="Identify bus labels from an ASC file.")
    identify_parser.add_argument("input_asc", help="Input ASC file.")
    identify_parser.add_argument("id2bus_json", help="JSON file generated by generate-id2bus.")
    identify_parser.add_argument("-O", "--output", help="Output JSON file.")
    identify_parser.add_argument( "-c", "--config-json", help="Configuration file for ignore IDs and ignore ID rules.")
    identify_parser.add_argument("-u", "--unique-label", action="store_true", help="Assume each bus label appears on only one ASC interface.")
    identify_parser.add_argument("-m", "--max-frames", type=int, default=10000, help="Maximum number of ASC frames to read.")
    identify_parser.add_argument("-v", "--verbosity", action="count", default=0, help="Increase output verbosity.")
    identify_parser.add_argument("--ignore-unknown-ids", action="store_true", help="Ignore CAN IDs that are not found in the id2bus map.")
    identify_parser.set_defaults(func=run_identify)

    return parser

def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)

if __name__ == "__main__":
    sys.exit(main())